services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoices
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"     

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    env_file: .env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "3001:3000"
    volumes:
      - ./apps/api:/app
      - ./prisma:/app/prisma
      - /app/node_modules
    command: sh -lc "npm i && npx prisma generate && npx prisma migrate dev --name init && npm run start:dev"

volumes:
  pgdata: {}
